version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: ci
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: build
    versioning-strategy: increase-if-necessary
